// Auto-generated file - DO NOT EDIT MANUALLY
// Generated by: scripts/generate-pixotope-icons.js
// Run 'npm run generate:pixotope-icons' to regenerate
//
// To add new icons:
// 1. Add your icon files to packages/fossflow-app/public/icons/pixotope/
// 2. Run: npm run generate:pixotope-icons
// 3. Restart your development server

export default [
  {
    "id": "pixotope-clock",
    "name": "Clock",
    "url": "/icons/pixotope/clock.png",
    "collection": "PIXOTOPE",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "pixotope-greenscreen",
    "name": "Greenscreen",
    "url": "/icons/pixotope/greenscreen.png",
    "collection": "PIXOTOPE",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "pixotope-led-floor",
    "name": "LED Floor",
    "url": "/icons/pixotope/led_floor.png",
    "collection": "PIXOTOPE",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "pixotope-led-wall",
    "name": "LED Wall",
    "url": "/icons/pixotope/led_wall.png",
    "collection": "PIXOTOPE",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "pixotope-light",
    "name": "Light",
    "url": "/icons/pixotope/light.png",
    "collection": "PIXOTOPE",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "pixotope-mixer",
    "name": "Audio Mixer",
    "url": "/icons/pixotope/mixer.png",
    "collection": "PIXOTOPE",
    "isIsometric": true,
    "scale": 1.1
  },
  {
    "id": "pixotope-video",
    "name": "Video Camera",
    "url": "/icons/pixotope/video.png",
    "collection": "PIXOTOPE",
    "isIsometric": true,
    "scale": 0.9
  }
];
